name: db-engine

on:
    push:
        branches:
        - '*'
    pull_request:
        - '*'
jobs:
    macos:
        runs-on: macos-latest 
        steps:
        - name: Checkout 
          uses: actions/checkout@v2 
        - name: Install Dependencies 
          run: |
              brew install boost 
        - name: Configure 
          run: |
              cd db-repo
              echo "${pwd}" && ls 
              sh ./build.sh
