name: CMake

on: [push, pull_request]

jobs:
  build:
    name: Check on ${{ matrix.os }}
    env:
      boost_version: "1.75.0"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install boost
      run: |
         wget -nv -O boost.tar.gz https://boostorg.jfrog.io/artifactory/main/release/${{ env.boost_version }}/source/boost_${{ env.boost_version }}.zip && 
         tar xzf boosti_${{ env.boost_version }}.zip -C ~/ && 
         ./bootstrap.sh && ./b2 && ./b2 install # install to default path /usr/local/lib, /usr/local/bin
    - name: cmake and build 
      run: |
         echo $(pwd) && sh ./build.sh      
    - name: Test
      run: echo "run test"
