name: CMake

on: [pull_request]

jobs:
  build:
    name: Check on ${{ matrix.os }}
    env:
      boost_version: "1.75.0"
      boost_version_name: "1_75_0"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install gtest 
      run: |
          echo $(pwd) &&  
          wget -nv -O /tmp/googletest-1.13.0.tar.gz https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz && 
          cd /tmp && tar xzf googletest-1.13.0.tar.gz &&  
          cd googletest-1.13.0/ && 
          mkdir -p ./build && cd build && cmake ../ && sudo make && sudo  make install && echo $(pwd) && ls * && 
          ls /usr/local/lib/libg* && ls /usr/local/include/gtest &&  
          echo "gtest installed ok" 
    - name: Install boost
      run: |
         echo $(pwd) && 
         wget -nv -O /tmp/boost.zip https://boostorg.jfrog.io/artifactory/main/release/${{ env.boost_version }}/source/boost_${{ env.boost_version_name }}.zip &&  
         cd /tmp && unzip boost.zip &&  cd boost_${{ env.boost_version_name }} && 
         ./bootstrap.sh && ./b2 && ./b2 install 
    - name: cmake and build 
      run: |
         echo $(pwd) && sh ./build.sh      
    - name: Test
      run: |
          echo "begin run ut tests $(pwd)" && 
          cd build/bin && ./unit_test_oss && 
          echo "finish run ut tests" 
