name: CMake

on:
  push:
    branches: [ "db_init" ]
  pull_request:
    branches: [ "db_init" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: build db-repo
      working-directory: ${{github.workspace}}/db-repo
      run: echo "${pwd}" && sh ./build.sh
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: echo "run test"
